### ISSUE TITLE
Maine isn't colorizing properly for Report Card

### ISSUE THREAD

**Issue by tolomaps** [yourbodynotyourchoice/yourbodynotyourchoice.github.io#1]
It's given the color of an F grade but is actually an A.
I took a quick look and couldn't figure it out. Will come back to this.
@kkowalsky or @DylanMoriarty: any thoughts as to what's going on?

**Comment by DylanMoriarty** [comment]
I'mma look into this quick, will update if I find anything.

**Comment by DylanMoriarty** [comment]
So, I have no idea why it was doing that... but I re-downloaded the CSV and it looks like it's working now! Neat.
