### ISSUE TITLE
Rhode Island not coloring/labeling properly

### ISSUE THREAD

**Issue by tolomaps** [yourbodynotyourchoice/yourbodynotyourchoice.github.io#2]
Got an email from someone who had stumbled upon our site saying that for "Prohibited At," Rhode Island's label says 24 weeks but the color is for 12 weeks.

**Comment by tolomaps** [comment]
After some more investigation, it looks like there are several issues with states that say 24 weeks but the color is for 12 weeks (RI, PA, SD). Texas is prohibited at 20 weeks but also has the color for 12 weeks. I'm not sure why the data isn't connecting up properly - maybe some weird thing like what happened with the [Maine](https://github.com/yourbodynotyourchoice/yourbodynotyourchoice.github.io/issues/1) issue.

**Comment by wneuheisel** [comment]
Looks likes its a case error in the CSV file. RI, PA, and SD have '24 Weeks' instead of '24 weeks', so it's probably just defaulting to the first value in the array (12 weeks) when it assigns the fill color.

**Comment by tolomaps** [comment]
Ha thanks @wneuheisel! We must've figured it out at the exact same time because I literally just changed it. :D
